### ISSUE TITLE
Response code : 403

### ISSUE THREAD

**Issue by ghost** [brahmkshatriya/echo-youtube-extension-old#5]
Few songs are unplayable with response code : 403. Happens even if login.

https://paste.rs/wPsox

**Comment by ghost** [comment]
Solved in yesterday's update

**Comment by ghost** [comment]
Issue persists in yt-cd1ce03.eapk

**Comment by Akelaphobia** [comment]
This randomly starts happening for me with all songs, even ones that previously worked fine, and doesn't fix itself until I wait a day or two. It seems to happen after maybe 30min-1hr of listening to music.

https://paste.rs/xEgnl

**Comment by joelalbert** [comment]
The Response 403 still persists after yesterday's extension update. Uninstalled extension, cleared cache of Echo, reinstalled extension again, still no luck.

https://paste.rs/oBFmD
https://paste.rs/f6o3l


Echo Version: v2.1.637_e11d0c7(637) nightly
Device: Redmi fog
Architecture: arm64-v8a
OS Version: REL 13 (33)

Extension version - v11d863a

**Comment by Abhishek890** [comment]
> The Response 403 still persists after yesterday's extension update. Uninstalled extension, cleared cache of Echo, reinstalled extension again, still no luck.
> 
> https://paste.rs/oBFmD https://paste.rs/f6o3l
> 
> Echo Version: v2.1.637_e11d0c7(637) nightly Device: Redmi fog Architecture: arm64-v8a OS Version: REL 13 (33)
> 
> Extension version - v11d863a

i tried to play the songs that not playing for you but they playing fine for me what you can do is 

i youtube music setting make sure you are signed in and keep prefer video on and stream quality off

Sometimes it's issue with network that get 403 i also get but when i switch from wifi to mobile same song i press again to play it play fine Sometimes YouTube is rate-limiting the device for your network try with mobile data and if you get 403 press that song 2-3 time so it can retry as youtube is rate-limiting request as i think
